return {
	Coins = 0,
	OwnedFolds = {
		["100"] = false,
		["200"] = false,
		["30"] = false,
		["50"] = false,
		["Default"] = true,
		["Group"] = false,
		["Normal"] = false,
		["VIP"] = false	
	},
	OwnedSkins = {
		["LoveSkin"] = false,
		["VoidSkin"] = false,
		["FlameSkin"] = false,
		["FrostSkin"] = false,

	},
	OwnedTrails = {
		
		["Blue"] = false,
		["Red"] = false,
		["Robux"] = false,
		["Star"] = false,
		["Rainbow"] = false,
		["Purple"] = false,
		["Luckybox"] = false,
		["Glide"] = false,
		["Fire"] = false,
		["Coin"] = false,		
		["Default"] = true
	},
	Potions = {
	["Jump"] = 0,
	["Speed"] = 0,
	["Luck"] = 0	
	},
	EquippedFold = "Default",
	EquippedSkin = "Default",
	EquippedTrail = "Default",	
	OwnedGamepasses = {
		["BoostSurge"] = false,
		["ButtonHighlight"] = false,	
		["SpeedCoil"] = false,
		["JumpCoil"] = false,
		["StarterPack"] = false,
		["VIP"] = false,

	},
	Settings = {
		Time = 12
	},
	UnlockedWorlds = {
		Earth = true,
	}
}
